spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_commerce_app
    username: user_e_commerce
    password: user_e_commerce

  flyway:
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: off

  data:
    rest:
      base-path: /api

  security:
    jwt:
      secret-key: H#hs{9Yi#@up8$#)9^68(c60_
      token-validity: 5000 # 5 seconds

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
