spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_commerce_app
    username: user_e_commerce
    password: user_e_commerce

  flyway:
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    rest:
      base-path: /api

server:
  port: 8080
