name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      working-directory: frontend

    - name: Build Angular app
      run: npm run build
      working-directory: frontend
