name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user_e_commerce
          POSTGRES_PASSWORD: user_e_commerce
          POSTGRES_DB: e_commerce_app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -f backend/pom.xml clean install
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/e_commerce_app
        SPRING_DATASOURCE_USERNAME: user_e_commerce
        SPRING_DATASOURCE_PASSWORD: user_e_commerce
